apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: autosync-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/shabgardetanha/AutoSync.git'
    targetRevision: main
    path: infra/auto-sync/overlays/dev
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
