apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# منابع پایه
resources:
  - deployment-autosync.yaml
  - featureflags-configmap.yaml

# ConfigMap Generator با تعیین behavior
configMapGenerator:
  - name: autosync-featureflags
    files:
      - featureflags-configmap.yaml
    behavior: merge   # یا replace اگر می‌خواهید overlay کاملاً جایگزین کند

# Secret Generator
secretGenerator:
  - name: autosync-secrets
    literals:
      - ff_api_key=CHANGE_ME
    type: Opaque

# Optional: namespace پیش‌فرض
# namespace: default
