apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment-autosync.yaml
  - featureflags-configmap.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: autosync-secrets
    literals:
      - ff_api_key=CHANGE_ME
    type: Opaque
    behavior: replace
