apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment-autosync.yaml
  - featureflags-configmap.yaml

secretGenerator:
  - name: autosync-secrets
    behavior: create
    literals:
      - ff_api_key=CHANGE_ME
    type: Opaque
