apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment-autosync.yaml
  - featureflags-configmap.yaml

secretGenerator:
  - name: autosync-secrets
    literals:
      - ff_api_key=Q0hBTkdFX01F
    behavior: replace   # ← این باعث می‌شود Secret هر بار جایگزین شود و خطا از بین برود

configMapGenerator:
  - name: autosync-featureflags
    files:
      - featureflags.yml

generatorOptions:
  disableNameSuffixHash: true 