apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - namespace.yaml
  - ../../base

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: autosync