apiVersion: apps/v1
kind: Deployment
metadata:
  name: autosync
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: autosync
          env:
            - name: ENV
              value: "dev"
