apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base
  - namespace.yaml
  - production-patch.yaml

patches:
  - path: production-patch.yaml
    target:
      kind: Production
      name: autosync