apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - namespace.yaml
  - ../../base

secretGenerator:
  - name: autosync-secrets
    literals:
      - ff_api_key=CHANGE_ME
    type: Opaque
    options:
      disableNameSuffixHash: true   # تا اسم secret ثابت بماند
