name: AutoSync Full CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # مرحله 1: Health-Check
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Health-Check
        run: python tools/health_check.py

  # مرحله 2: Core Execution
  core:
    needs: health_check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Core Engine
        run: python tools/run_core.py

  # مرحله 3: Patch & Test
  patch_test:
    needs: core
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Patch & Test
        run: python tools/run_patch_test.py

  # مرحله 4: Dashboard
  dashboard:
    needs: patch_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Dashboard
        run: python tools/run_dashboard.py

  # مرحله 5: Notifications
  notifications:
    needs: dashboard
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Notifications
        run: python tools/run_notifications.py

  # مرحله 6: Analytics & Feedback
  analytics:
    needs: notifications
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Analytics & Feedback
        run: python tools/run_analytics.py

  # مرحله 7: Deployment / Demo
  deploy:
    needs: analytics
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Auto Version Bump
        run: |
          echo "🟦 Running auto_version_bump.py ..."
          python core/utils/auto_version_bump.py

      - name: Deploy Demo / Training Package
        run: python tools/deploy_demo.py

      - name: Run Test Suite
        run: |
          if [ -f tests/run_tests.py ]; then
            python tests/run_tests.py
          else
            echo "No tests/run_tests.py found — skipping tests."
          fi

      - name: Generate AutoSync Summary Report
        run: |
          python tools/auto_report.py

      - name: Commit & Push Summary Report
        env:
          GIT_COMMITTER_NAME: "AutoSync Bot"
          GIT_COMMITTER_EMAIL: "autosync-bot@system.local"
        run: |
          git config user.name "$GIT_COMMITTER_NAME"
          git config user.email "$GIT_COMMITTER_EMAIL"
          git add docs/summary_final.md || true
          git commit -m "Auto-generated summary report [skip ci]" || echo "No changes to commit"
          git push origin HEAD:main || echo "Push failed or nothing to push"

      - name: Finish
        run: echo "CI/CD pipeline finished."
