name: Flyway Migrations

on:
  workflow_dispatch:

jobs:
  flyway_migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flyway (use Flyway Community via Docker)
        run: |
          docker run --rm -v ${PWD}/infra/auto-sync/flyway:/flyway/sql flyway/flyway:latest -url=${{ secrets.FLYWAY_URL }} -user=${{ secrets.FLYWAY_USER }} -password=${{ secrets.FLYWAY_PASSWORD }} migrate
